#!/bin/sh

# take a number, with a possible G M or K ending and make it normal
# This the format with cgroups uses - it should not be used for anything else
function cgroupSerialize {

local i=$1

LCHAR="${i: -1}"
#now make lower case
LCHAR="${LCHAR,,}"

V_K=1024
V_M=1048576
V_G=1073741824
V_T=1099511627776

NUM=$(echo $i |tr -cd 0-9)

case $LCHAR in
k)
RETURN_VAL=$(($NUM * $V_K))
;;
m)
RETURN_VAL=$(($NUM * $V_M))
;;
g)
RETURN_VAL=$(($NUM * $V_G))
;;
t)
RETURN_VAL=$(($NUM * $V_T))
;;
*)
RETURN_VAL=$i
;;
esac

return
}
