#!/bin/sh

function configMem () {

#output of title screen as a reminder RSS: 
#
# ${GUESTS_MEMALLOC_H[$i]}/${GUESTS_MEMCURRENT_H[$i]}/${GUESTS_MEMMAX_H[$i]} 
# SWP: ${GUESTS_SWPALLOC_H[$i]}/${GUESTS_SWPCURRENT_H[$i]}/${GUESTS_SWPMAX_H[$i]} 
# (Allocated/Current/Max)
# So, this module will only need the parameter we already have from the initial info sweep, it doesn't need to get anything more.

local i=$1

$DIALOG  --title "Memory Configuration" --ok-label "Submit" \
         --backtitle  "$(cat $LANG_LOC/name)" \
         --mixedform "Set the memory parameters here for ${GUESTS[$i]}." 25 80 0 \
          "Allocated Memory       :" 2 1 "${GUESTS_MEMALLOC_H[$i]}"   2 25 20 0 0 \
          "Current Memory         :" 3 1 "${GUESTS_MEMCURRENT_H[$i]}" 3 25 20 0 2 \
          "Max Used Memory        :" 4 1 "${GUESTS_MEMMAX_H[$i]}"     4 25 20 0 2 \
          "Allocated Memory       :" 5 1 "${GUESTS_SWPALLOC_H[$i]}"   5 25 20 0 0 \
          "Current Memory         :" 6 1 "${GUESTS_SWPCURRENT_H[$i]}" 6 25 20 0 2 \
          "Max Used Memory        :" 7 1 "${GUESTS_SWPMAX_H[$i]}"     7 25 20 0 2 \
          "Apply Live? Y/N        :" 8 1 "Y"                          8 25 1 0 0 \
          "Aplly persistently? Y/N:" 9 1 "Y"                          9 25 1 0 0 \



if [ "$DEBUG" = "1" ]; then
  sleep 5
fi

return
}
