#!/bin/bash

function guestConfigure {

local MENUMASS=( )
local p=0
local i=$1

GC_BASENAME="$(cat $LANG_LOC/gc_basename)"
GC_HOSTNAME="$(cat $LANG_LOC/gc_hostname)"
GC_GUESTNAME="$(cat $LANG_LOC/gc_guestname)"
GC_MEMALL="$(cat $LANG_LOC/gc_memall)"
GC_EXIT="$(cat $LANG_LOC/gc_exit)"

#TODO replace with strings

#Guest name
MENUMASS[$p]="${GC_BASENAME}"
((p++))
MENUMASS[$p]="${GUESTS[$VSID]}"
((p++))
MENUMASS[$p]="Basename of server's config dir"
((p++))

#Node name
MENUMASS[$p]="${GC_HOSTNAME}"
((p++))
MENUMASS[$p]="$(cat $VCONF_LOC/${GUESTS[$i]}/uts/nodename)"
((p++))
MENUMASS[$p]="The hostname as given in /uts/nodename"
((p++))

#Name
MENUMASS[$p]="${GC_GUESTNAME}"
((p++))
#TODO, if exists then else = basename
MENUMASS[$p]="$(cat $VCONF_LOC/${GUESTS[$i]}/name)"
((p++))
MENUMASS[$p]="The guests name, as it will appear in vserver-stat for example"
((p++))

#Memory name
MENUMASS[$p]="${GC_MEMALL}"
((p++))
MENUMASS[$p]="${GUESTS_MEMALLOC_H[$i]}"
((p++))
MENUMASS[$p]="Current Use: ${GUESTS_MEMCURRENT_H[$i]}  Max Historical Use: ${GUESTS_MEMMAX_H[$i]}"
((p++))

$DIALOG --clear --column-separator "%" --item-help\
 --backtitle "$(cat $LANG_LOC/name)"\
 --title "${GUESTS[$VSID]}" --menu "Welcome" 22 75 68\
 "${MENUMASS[@]}" 2>"${INPUT}"

#exit on cancel
if [ "$?" = "1" ]; then
  RETURN_VAL="exitloop"
fi

local MENUITEM=$(<"${INPUT}")

case "${MENUITEM}" in
   ${GC_BASENAME})
      RETURN_VAL="basename"
   ;;
   ${GC_HOSTNAME})
      RETURN_VAL="hostname"
   ;;
   ${GC_GUESTNAME})
      RETURN_VAL="guestname"
   ;;
   ${GC_MEMALL})
      RETURN_VAL="memall"
   ;;
esac

return
}

