#!/bin/sh

function mainMenu {

# Consider converting from and to number formats with numfmt --from=??

# This section fills an array which is then put into $DIALOG
# it appears the only way to put a bunch of separate inputs
# into a command.
local MENUMASS=( )
local p=0
local i=0
for (( i=0; i<${#GUESTS[@]}; i++ )); do
#name
MENUMASS[$p]="${GUESTS[$i]}"
((p++))
#columns
if [ "${GUESTS_RUNNING[$i]}" = "1" ]; then
MENUMASS[$p]="${CROSS}%"
else
MENUMASS[$p]="${TIC}%"
fi
if [ "${GUESTS_MARKED[$i]}" = "1" ]; then
MENUMASS[$p]="${MENUMASS[$p]}${CROSS}%"
else
MENUMASS[$p]="${MENUMASS[$p]}${TIC}%"
fi
MENUMASS[$p]="${MENUMASS[$p]}$(cat $VCONF_LOC/${GUESTS[$i]}/context)"
((p++))
#give item number for now, add details later
MENUMASS[$p]="RSS: ${GUESTS_MEMALLOC_H[$i]}/${GUESTS_MEMCURRENT_H[$i]}/${GUESTS_MEMMAX_H[$i]}  SWP: ${GUESTS_SWPALLOC_H[$i]}/${GUESTS_SWPCURRENT_H[$i]}/${GUESTS_SWPMAX_H[$i]} (ALL/NOW/MAX)"
((p++))
done

$DIALOG --clear --default-item "${GUESTS[0]}" --column-separator "%"\
 --item-help\
 --title "$(cat $LANG_LOC/name) - Pick a guest" --menu "Welcome" 18 75 68\
 "NAME" "On%Mark%XID" ""\
 "${MENUMASS[@]}" 2>"${INPUT}"

SELECTED=$(<"${INPUT}")

# TODO if exit then exit, and so on

# Convert selected server into the internal ID
for (( i=0; i<${#GUESTS[@]}; i++ )); do
if [ "${GUESTS[$i]}" = "${SELECTED}" ]; then
RETURN_VAL="${i}"
fi
done

return
}
