#!/bin/sh

function testInstall {

dialog > /dev/null 2>&1
if [ "$?" = "0" ]; then
   if [ "$DEBUG" = "1" ]; then
     echo "Dialog is installed, proceeding."
   fi
else
   echo "Please install 'dialog'."
   exit 1
fi

if [ -d $CONF_LOC ]; then
  echo "Install directory exists and contains config."
  return 0
else
  echo "Install directory does not exist or does not contain the expected files, perhaps edit /etc/default/vcute."
  exit 1
fi

if [ "$DEBUG" = "1" ]; then
  debugPause
fi


}
