#!/bin/bash

# Commented out - but should be changed to where
# you put checked out the git repo.
# INSTALL_DIR=""

DIALOG=/usr/bin/dialog
CONF_LOC=${INSTALL_DIR}/etc/vcute
#fix - get this from conf
VDIR_LOC=/home/vservers
#fix - get this from conf (compile output of util-vserver?)
VCONF_LOC=/etc/vservers
LIB_LOC=${INSTALL_DIR}/usr/share/vcute/lib
LANG_LOC=${INSTALL_DIR}/usr/share/vcute/lang/en_GB
CGROUP_LOC="/dev/cgroup"
# can be "same" or "split" depending on how the groups are mounted
CGROUP_FORMAT="same"
#CGROUP_FORMAT="split"

